### ISSUE TITLE
Failing on startup

### ISSUE THREAD

**Issue by samcro1967** [barrycarey/Speedtest-for-InfluxDB-and-Grafana#24]
My speedtest script stopped working on 1/26/19 at 22:30 PM CST.  Below is the error in the logs when it tries to run,  The server filed in my config.ini is blank.  I am running telegraf and data from it is still being inserted into influxDB so I do not believe it is a DB problem.

  File "/src/influxspeedtest/config/configmanager.py", line 37, in _load_config_values,
    self.logging_level = self.config['LOGGING'].get('Level', fallback='debug'),
  File "/usr/local/lib/python3.7/configparser.py", line 958, in __getitem__,
    raise KeyError(key),
KeyError: 'LOGGING',
Loading Configuration File config.ini,
Traceback (most recent call last):,
  File "/src/influxspeedtest.py", line 3, in <module>,
    from influxspeedtest.InfluxdbSpeedtest import InfluxdbSpeedtest,
  File "/src/influxspeedtest/InfluxdbSpeedtest.py", line 9, in <module>,
    from influxspeedtest.common import log,
  File "/src/influxspeedtest/common/__init__.py", line 1, in <module>,
    from .utils import log,
  File "/src/influxspeedtest/common/utils.py", line 5, in <module>,
    from influxspeedtest.config import config,
  File "/src/influxspeedtest/config/__init__.py", line 10, in <module>,
    config = ConfigManager(config),
  File "/src/influxspeedtest/config/configmanager.py", line 19, in __init__,
    self._load_config_values(),
  File "/src/influxspeedtest/config/configmanager.py", line 37, in _load_config_values,
    self.logging_level = self.config['LOGGING'].get('Level', fallback='debug'),
  File "/usr/local/lib/python3.7/configparser.py", line 958, in __getitem__,
    raise KeyError(key),

**Comment by barrycarey** [comment]
Looks like the logging section is missing from the config.  This was a bug in a commit from a few days ago. 

Ad this to the bottom of the config: 

[LOGGING]
Level = info

**Comment by samcro1967** [comment]
That fixed it.  Thanks!
